<?php

namespace ContainerP0N2RG1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UhPBEXpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UhPBEXp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UhPBEXp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\EventController::delete' => ['privates', '.service_locator.kyRmj3Q', 'get_ServiceLocator_KyRmj3QService', true],
            'App\\Controller\\EventController::edit' => ['privates', '.service_locator.kyRmj3Q', 'get_ServiceLocator_KyRmj3QService', true],
            'App\\Controller\\EventController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\EventController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\EventController::show' => ['privates', '.service_locator.wLYTQQR', 'get_ServiceLocator_WLYTQQRService', true],
            'App\\Controller\\ProdController::delete' => ['privates', '.service_locator.Niycchk', 'get_ServiceLocator_NiycchkService', true],
            'App\\Controller\\ProdController::edit' => ['privates', '.service_locator.Niycchk', 'get_ServiceLocator_NiycchkService', true],
            'App\\Controller\\ProdController::index' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Controller\\ProdController::new' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Controller\\ProdController::show' => ['privates', '.service_locator.5OibA2.', 'get_ServiceLocator_5OibA2_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\EventController:delete' => ['privates', '.service_locator.kyRmj3Q', 'get_ServiceLocator_KyRmj3QService', true],
            'App\\Controller\\EventController:edit' => ['privates', '.service_locator.kyRmj3Q', 'get_ServiceLocator_KyRmj3QService', true],
            'App\\Controller\\EventController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\EventController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\EventController:show' => ['privates', '.service_locator.wLYTQQR', 'get_ServiceLocator_WLYTQQRService', true],
            'App\\Controller\\ProdController:delete' => ['privates', '.service_locator.Niycchk', 'get_ServiceLocator_NiycchkService', true],
            'App\\Controller\\ProdController:edit' => ['privates', '.service_locator.Niycchk', 'get_ServiceLocator_NiycchkService', true],
            'App\\Controller\\ProdController:index' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Controller\\ProdController:new' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Controller\\ProdController:show' => ['privates', '.service_locator.5OibA2.', 'get_ServiceLocator_5OibA2_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\EventController::delete' => '?',
            'App\\Controller\\EventController::edit' => '?',
            'App\\Controller\\EventController::index' => '?',
            'App\\Controller\\EventController::new' => '?',
            'App\\Controller\\EventController::show' => '?',
            'App\\Controller\\ProdController::delete' => '?',
            'App\\Controller\\ProdController::edit' => '?',
            'App\\Controller\\ProdController::index' => '?',
            'App\\Controller\\ProdController::new' => '?',
            'App\\Controller\\ProdController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\EventController:delete' => '?',
            'App\\Controller\\EventController:edit' => '?',
            'App\\Controller\\EventController:index' => '?',
            'App\\Controller\\EventController:new' => '?',
            'App\\Controller\\EventController:show' => '?',
            'App\\Controller\\ProdController:delete' => '?',
            'App\\Controller\\ProdController:edit' => '?',
            'App\\Controller\\ProdController:index' => '?',
            'App\\Controller\\ProdController:new' => '?',
            'App\\Controller\\ProdController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
