index:
    path: /
    controller: App\Controller\IndexController::index

cart:
    path: /cart
    controller: App\Controller\CartController::index

product:
    path: /product
    controller: App\Controller\ProductController::index

product-details:
    path: /product-details
    controller: App\Controller\ProductDetailsController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::index


blog-single:
    path: /blog-single
    controller: App\Controller\BlogSingelController::index


blog:
    path: /blog
    controller: App\Controller\BlogController::index

login:
    path: /security/login
    controller: App\Controller\UserController::login

checkout:
    path: /checkout
    controller: App\Controller\CheckoutController::index


notFound:
    path: /notFound
    controller: App\Controller\NotFoundController::index
    
Inscription:
    path: /user/new
    controller: App\Controller\UserController::new

Admin:
    path: /user
    controller: App\Controller\UserController::index

user_profile:
    path: /user_profile
    controller: App\Controller\UserController::profile


app_product_details:
    path: /product-details/{id}
    controller: App\Controller\ProductDetailsController::index
pdf:
    path: /pdf/{id}
    controller: App\Controller\UserController::pdf


      
app_password_reset:
  path: /password-reset
  controller: App\Controller\UserController::passwordReset
exel:
    path: /user/exel
    controller: App\Controller\UserController::indexexel