<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPbFMJCx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPbFMJCx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPbFMJCx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPbFMJCx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPbFMJCx\App_KernelDevDebugContainer([
    'container.build_hash' => 'PbFMJCx',
    'container.build_id' => '333b4c98',
    'container.build_time' => 1681252351,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPbFMJCx');
