<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP0N2RG1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP0N2RG1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP0N2RG1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP0N2RG1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP0N2RG1\App_KernelDevDebugContainer([
    'container.build_hash' => 'P0N2RG1',
    'container.build_id' => 'bcca5a31',
    'container.build_time' => 1681160193,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP0N2RG1');
